### ISSUE TITLE
Padding not configurable

### ISSUE THREAD

**Issue by DBinaghi** [omeka/plugin-CollectionTree#33]
I believe there is an issue with the padding for collections list: in `models/Table/CollectionTree.php` it's supposed to be passable as a parameter, but then it's hardcoded ignoring the parameter.

I suggest to remove the following code from **findPairsForSelectForm** function:

```
        if (isset($params['padding'])) {
            $padding = $params['padding'];
        } else {
            $padding = '-';
        }
```

**Comment by zerocrates** [comment]
I'm going to go the other way and listen only to a `padding` passed into the `$options` array, just to keep the signature in line with other instances of this same method. (That still involves a change to this snippet to look at `$options` and not the nonexistent `$params`.)

That change is included in 38e6989cac855e59294f5483dd46cb205ce2fcb6
