### ISSUE TITLE
advanced search field mislabeled

### ISSUE THREAD

**Issue by DigExpCon** [omeka/plugin-CollectionTree#36]
On the advanced search form, the field "Expand to subcollections" has a label 'for="public"', but the 'public' field ID is already used by the search-by-public field, and the checkbox of the 'Expand to subcollections' field has the ID 'subcollections'. 

Hence, on line 332 of /CollectionTree/CollectionTreePlugin.php the label should be changed to 'for-"subcollections"'.

**Comment by zerocrates** [comment]
This was fixed a little while ago (you'll see if you look at the relevant line here on Github). We just haven't released a new version yet that contains the fix.
